//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HideRugs.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Table_1
    {
        public int ID { get; set; }
        public string Image { get; set; }
        [Required(ErrorMessage = "Hide name is required.")]
        public string Hide { get; set; }
        [Required(ErrorMessage = "Hide type is required.")]
        public string Type { get; set; }
        [Required(ErrorMessage = "Size is required")]
        public string Size { get; set; }
        [Required(ErrorMessage = "Colour is required.")]
        public string Colour { get; set; }
        [Range(0, 100000, ErrorMessage = "Please enter a valid number between 0 - 100,000")]
        public Nullable<decimal> Price { get; set; }
        [Range(0, 100000, ErrorMessage = "Please enter a valid number between 0 - 100,000")]
        public Nullable<int> Stock { get; set; }
        public string Description { get; set; }
        [Required(ErrorMessage = "Product ID is required.")]
        public string ProductID { get; set; }
        [DataType(DataType.MultilineText)]
        public string Additional { get; set; }

    }
}
