//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HideRugs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table1
    {
        public int ID { get; set; }
        public string Animal { get; set; }
        public string Type { get; set; }
        public string Colour { get; set; }
        public string Size { get; set; }
        public string ProductID { get; set; }
        public string Picture { get; set; }
    }
}
