//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameOfThrones.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Character
    {
        public int Id { get; set; }
        public string Image { get; set; }
        [Required(ErrorMessage = "Name is required.")]
        public string Name { get; set; }

        public string Titles { get; set; }
        public string Origin { get; set; }
        public Nullable<int> HouseId { get; set; }
        [Required(ErrorMessage = "Status is required.")]
        public string Status { get; set; }
        public string Death { get; set; }
        public string Actor { get; set; }
    
        public virtual House House { get; set; }
    }
}
